const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const newProducts = [
  {
    name: "Phantom Gaming Headset",
    description: "Over-ear gaming headset with 7.1 surround sound, detachable microphone, and RGB lighting. Memory foam cushions for extended comfort during marathon sessions.",
    price: 4499,
    originalPrice: 5999,
    category: "Gaming",
    brand: "DropCart Gaming",
    images: JSON.stringify(["https://images.unsplash.com/photo-1599669454699-248893623440?w=600&h=600&fit=crop"]),
    stock: 35,
    rating: 4.7,
    reviewsCount: 189,
    featured: true,
    tags: JSON.stringify(["gaming", "headset", "rgb"]),
  },
  {
    name: "Minimalist Leather Wallet",
    description: "Slim RFID-blocking wallet crafted from full-grain vegetable-tanned leather. Holds 8 cards and cash with minimal bulk. Ages beautifully over time.",
    price: 1299,
    originalPrice: 1799,
    category: "Accessories",
    brand: "DropCart Essentials",
    images: JSON.stringify(["https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&h=600&fit=crop"]),
    stock: 80,
    rating: 4.5,
    reviewsCount: 234,
    featured: false,
    tags: JSON.stringify(["wallet", "leather", "minimalist"]),
  },
  {
    name: "Ceramic Pour-Over Set",
    description: "Handcrafted ceramic dripper and server set for perfect pour-over coffee. Includes reusable stainless steel filter. Matte black finish with wooden handle.",
    price: 2199,
    originalPrice: 2999,
    category: "Home & Kitchen",
    brand: "DropCart Living",
    images: JSON.stringify(["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop"]),
    stock: 25,
    rating: 4.8,
    reviewsCount: 67,
    featured: false,
    tags: JSON.stringify(["coffee", "kitchen", "ceramic"]),
  },
  {
    name: "Arctic Down Puffer Jacket",
    description: "800-fill power goose down jacket with water-resistant shell and DWR coating. Packable design compresses into its own pocket. Rated to -20°C.",
    price: 8999,
    originalPrice: 12499,
    flashSalePrice: 6999,
    category: "Apparel",
    brand: "DropCart Outdoor",
    images: JSON.stringify(["https://images.unsplash.com/photo-1544923246-77307dd270b5?w=600&h=600&fit=crop"]),
    stock: 18,
    rating: 4.9,
    reviewsCount: 98,
    featured: true,
    tags: JSON.stringify(["jacket", "winter", "flash-sale"]),
  },
  {
    name: "Mechanical Keyboard 75%",
    description: "Hot-swappable mechanical keyboard with PBT keycaps, gasket mount, and south-facing RGB. Cherry MX compatible switches. USB-C with Bluetooth 5.0.",
    price: 6499,
    originalPrice: 7999,
    category: "Electronics",
    brand: "DropCart Tech",
    images: JSON.stringify(["https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&h=600&fit=crop"]),
    stock: 42,
    rating: 4.6,
    reviewsCount: 156,
    featured: true,
    tags: JSON.stringify(["keyboard", "mechanical", "tech"]),
  },
  {
    name: "Titanium Water Bottle",
    description: "Double-wall vacuum insulated titanium bottle. Keeps drinks cold 24h or hot 12h. Ultra-lightweight at just 280g. BPA-free with leak-proof lid.",
    price: 1799,
    originalPrice: 2299,
    category: "Sports",
    brand: "DropCart Outdoor",
    images: JSON.stringify(["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop"]),
    stock: 90,
    rating: 4.4,
    reviewsCount: 312,
    featured: false,
    tags: JSON.stringify(["bottle", "sports", "outdoor"]),
  },
  {
    name: "Canvas Tote Bag",
    description: "Heavy-duty organic canvas tote with reinforced stitching and interior zip pocket. Screen-printed DropCart logo. Perfect for daily carry.",
    price: 999,
    originalPrice: 1499,
    category: "Accessories",
    brand: "DropCart Originals",
    images: JSON.stringify(["https://images.unsplash.com/photo-1597633425046-08f5110420b5?w=600&h=600&fit=crop"]),
    stock: 120,
    rating: 4.3,
    reviewsCount: 89,
    featured: false,
    tags: JSON.stringify(["tote", "bag", "canvas"]),
  },
  {
    name: "Wireless Charging Pad",
    description: "15W fast wireless charger with anti-slip silicone surface. Compatible with all Qi-enabled devices. LED indicator with auto sleep mode.",
    price: 1499,
    originalPrice: 1999,
    category: "Electronics",
    brand: "DropCart Tech",
    images: JSON.stringify(["https://images.unsplash.com/photo-1591290473781-1ef62f1f4f32?w=600&h=600&fit=crop"]),
    stock: 65,
    rating: 4.2,
    reviewsCount: 178,
    featured: false,
    tags: JSON.stringify(["charger", "wireless", "tech"]),
  },
  {
    name: "Retro Running Shoes",
    description: "Vintage-inspired suede and mesh running shoes with modern cushioning technology. Available in Heritage Green colorway with gum sole.",
    price: 4799,
    originalPrice: 5999,
    category: "Footwear",
    brand: "DropCart Sport",
    images: JSON.stringify(["https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&h=600&fit=crop"]),
    stock: 33,
    rating: 4.6,
    reviewsCount: 134,
    featured: false,
    tags: JSON.stringify(["shoes", "retro", "running"]),
  },
  {
    name: "Bamboo Desk Organizer",
    description: "Multi-compartment desk organizer made from sustainable bamboo. Features phone stand, pen holders, and cable management slots. Natural finish.",
    price: 1599,
    originalPrice: 2199,
    category: "Home & Kitchen",
    brand: "DropCart Living",
    images: JSON.stringify(["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop"]),
    stock: 50,
    rating: 4.5,
    reviewsCount: 45,
    featured: false,
    tags: JSON.stringify(["desk", "organizer", "bamboo"]),
  },
  {
    name: "Sport Compression Socks",
    description: "Graduated compression socks for athletic performance and recovery. Moisture-wicking fabric with arch support. Pack of 3 pairs.",
    price: 899,
    originalPrice: 1299,
    category: "Sports",
    brand: "DropCart Sport",
    images: JSON.stringify(["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop"]),
    stock: 150,
    rating: 4.1,
    reviewsCount: 267,
    featured: false,
    tags: JSON.stringify(["socks", "compression", "sports"]),
  },
  {
    name: "Graphic Print T-Shirt",
    description: "100% organic cotton crew neck tee with original DropCart artwork. Pre-shrunk, enzyme-washed for an ultra-soft feel. Relaxed unisex fit.",
    price: 1299,
    originalPrice: 1699,
    category: "Apparel",
    brand: "DropCart Originals",
    images: JSON.stringify(["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop"]),
    stock: 75,
    rating: 4.4,
    reviewsCount: 198,
    featured: false,
    tags: JSON.stringify(["tshirt", "graphic", "cotton"]),
  },
];

async function main() {
  console.log("🌱 Seeding 12 additional products...");
  for (const product of newProducts) {
    await prisma.product.create({ data: product });
  }
  const total = await prisma.product.count();
  console.log(`✅ Done! Total products in database: ${total}`);
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
